const bannedWords = [
      "Abuso", "Acojonar", "Afollonada", "Afollonado", "Agilipollada", "Agilipollado", 
      "Agilipollar", "Alamierda", "Amamonada", "Amamonado", "Amargada", "Amargado",
      "Anárquico", "Anormal", "Asesina", "Asesinar", "Asesino", "Asquerosa", 
      "Asqueroso", "Autoritaria", "Autoritario", "Autoritarismo", "Badajo", "Bastarda", 
      "Bastardo", "Basura", "Berzas", "Berzotas", "Bestia", "Boba", "Bobo", "Bollera", 
      "Boluda", "Boludez", "Boludo", "Borracha", "Borrachaza", "Borrachazo", "Borrachera", 
      "Borracho", "Borrachuza", "Borrachuzo", "Bronca", "Bufón", "Bufona", "Bujarra", 
      "Bujarrilla", "Bujarrón", "Cabreada", "Cabreado", "Cabrear", "Cabreo", "Cabrón", 
      "Cabrona", "Cabronada", "Cabroncete", "Caca", "Cachonda", "Cachondeo", "Cachondo", 
      "Cagada", "Cagado", "Cagar", "Cagarla", "Cagarse", "Cagoen", "Cagón", "Cagona", 
      "Calentorra", "Calentorro", "Calzonazo", "Calzonazos", "Camero", "Capulla", "Capullo", 
      "Carajo", "Carajota", "Carajote", "Carallo", "Carnudo", "Cascar", "Cascarla", "Casquete", 
      "Cateta", "Cateto", "Cazurra", "Cazurro", "Cencular", "Cenutrio", "Cepillar", "Ceporra", 
      "Ceporro", "Chapero", "Chaquetera", "Chaquetero", "Chichi", "Chingada", "Chingar", 
      "Chivata", "Chivato", "Chocho", "Chochona", "Choriza", "Chorizo", "Chorra", "Chorrada", 
      "Chorva", "Chula", "Chulilla", "Chulillo", "Chulita", "Chulito", "Chulo", "Chuloputas", 
      "Chumino", "Chúpame", "Chúpamela", "Chupópteros", "Churra", "Churrita", "Chutarse", 
      "Chute", "Cipote", "Cipotón", "Cojón", "Cojones", "Cojonudo", "Comemierda", "Comino", 
      "Coño", "Cornuda", "Cornudo", "Correrse", "Corrida", "Corrupta", "Corrupto", "Cretina", 
      "Cretino", "Cuerno", "Cuesco", "Culear", "Culero", "Cutre", "Decapitar", "Decojones", 
      "Degollar", "Descojonarse", "Descojone", "Descojono", "Desequilibrada", "Desequilibrado", 
      "Desgraciada", "Desgraciado", "Déspota", "Dictatorial", "Doctorcilla", "Doctorcillo", 
      "Doctorcita", "Doctorcito", "Drogata", "Embustera", "Embustero", "Encabronar", "Encubrimiento", 
      "Encular", "Enganchada", "Enganchado", "Engañabobos", "Engañar", "Engaño", "Enmascaramiento",
      "No es mi trabajo", "No me pagan lo suficiente para hacer eso",
  "Eso es gay", "Eso es para chicas",
  "Eso es para negros", "Eso es para blancos",
  "Eso es para discapacitados", "Eso es para locos",
  "Eso es para viejos", "Eso es para jóvenes",
  "Eso es para gordos", "Eso es para flacos",
  "Eso es para pobres", "Eso es para ricos",
  "Eso es para feos", "Eso es para guapos",
  "Eso es para tontos", "Eso es para inteligentes",
  "Eso es para hombres", "Eso es para mujeres",
  "Puto maricon",
  "Puto maricon tonto",
  "bombisa",
  "hijo de tu madre",
  "",

    ];
    
    export default bannedWords;